/**
 * The app's icon set: Phosphor (regular weight), a consistently drawn professional family.
 * Exported under the names the pages already use, so swapping the set is one file.
 * Every icon accepts `size` and `className`.
 */
export {
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowsClockwise as RefreshCw,
  BatteryHigh as Battery,
  Bell,
  BellRinging as BellRing,
  BellSlash as BellOff,
  Broadcast as Radio,
  Camera,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  ChartBar as ChartNoAxesColumn,
  Check,
  CheckCircle as CheckCircle2,
  CheckCircle as CircleCheck,
  Checks as CheckCheck,
  CircleNotch as Loader2,
  Clock,
  CloudSun,
  Copy,
  Cpu,
  DownloadSimple as Download,
  Drop as Droplets,
  Envelope as Mail,
  Eye,
  EyeSlash as EyeOff,
  FileText,
  GasPump as Fuel,
  Gauge,
  GearSix as Settings,
  GpsFix as Satellite,
  Handshake,
  Info,
  Key as KeyRound,
  Leaf,
  LinkSimple as Link2,
  List as Menu,
  Lock,
  MagnifyingGlass as Search,
  MapPin,
  MapTrifold as MapPinned,
  Package,
  Package as PackageCheck,
  Path as Bot,
  Plant as Sprout,
  Play,
  Plugs as PlugZap,
  Plus,
  Pulse as Activity,
  SealCheck as BadgeCheck,
  ShieldCheck,
  ShieldWarning as ShieldAlert,
  SignOut as LogOut,
  Snowflake,
  SquaresFour as LayoutDashboard,
  ThermometerSimple as Thermometer,
  TrafficCone,
  Truck,
  User as UserRound,
  UsersThree as Users,
  Warning as AlertTriangle,
  Warning as TriangleAlert,
  WarningCircle as CircleAlert,
  X,
  XCircle,
} from '@phosphor-icons/react'
