using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using WonderFleet.Domain.Entities;

namespace WonderFleet.Infrastructure.Persistence.Configurations;

// Keys are UUIDv7 generated by the application. ValueGeneratedNever makes EF INSERT (not UPDATE)
// new children discovered through navigations. Column names are snake_cased by ApplicationDbContext.

internal sealed class AdminUserConfiguration : IEntityTypeConfiguration<AdminUser>
{
    public void Configure(EntityTypeBuilder<AdminUser> b)
    {
        b.ToTable("admin_users");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.HasMany(x => x.RefreshTokens).WithOne().HasForeignKey(t => t.AdminUserId).OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class RefreshTokenConfiguration : IEntityTypeConfiguration<RefreshToken>
{
    public void Configure(EntityTypeBuilder<RefreshToken> b)
    {
        b.ToTable("refresh_tokens");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class LogisticsPartnerConfiguration : IEntityTypeConfiguration<LogisticsPartner>
{
    public void Configure(EntityTypeBuilder<LogisticsPartner> b)
    {
        b.ToTable("logistics_partners");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.HasMany(x => x.TruckTypes).WithOne().HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Cascade);
        b.HasMany(x => x.Corridors).WithOne().HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Cascade);
        b.HasMany(x => x.Documents).WithOne().HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Cascade);
        b.HasMany(x => x.Drivers).WithOne(x => x.LogisticsPartner).HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Restrict);
        b.HasMany(x => x.Vehicles).WithOne(x => x.LogisticsPartner).HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Restrict);
    }
}

internal sealed class PartnerTruckTypeConfiguration : IEntityTypeConfiguration<PartnerTruckType>
{
    public void Configure(EntityTypeBuilder<PartnerTruckType> b)
    {
        b.ToTable("partner_truck_types");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class PartnerCorridorConfiguration : IEntityTypeConfiguration<PartnerCorridor>
{
    public void Configure(EntityTypeBuilder<PartnerCorridor> b)
    {
        b.ToTable("partner_corridors");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class PartnerDocumentConfiguration : IEntityTypeConfiguration<PartnerDocument>
{
    public void Configure(EntityTypeBuilder<PartnerDocument> b)
    {
        b.ToTable("partner_documents");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class AgroProcessorConfiguration : IEntityTypeConfiguration<AgroProcessor>
{
    public void Configure(EntityTypeBuilder<AgroProcessor> b)
    {
        b.ToTable("agro_processors");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.Ignore(x => x.PrimaryContact);
        b.HasMany(x => x.Contacts).WithOne().HasForeignKey(x => x.AgroProcessorId).OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class AgroProcessorContactConfiguration : IEntityTypeConfiguration<AgroProcessorContact>
{
    public void Configure(EntityTypeBuilder<AgroProcessorContact> b)
    {
        b.ToTable("agro_processor_contacts");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class DriverConfiguration : IEntityTypeConfiguration<Driver>
{
    public void Configure(EntityTypeBuilder<Driver> b)
    {
        b.ToTable("drivers");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class VehicleConfiguration : IEntityTypeConfiguration<Vehicle>
{
    public void Configure(EntityTypeBuilder<Vehicle> b)
    {
        b.ToTable("vehicles");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.Property(x => x.Version).HasColumnName("xmin").HasColumnType("xid").ValueGeneratedOnAddOrUpdate().IsConcurrencyToken();
        // "L per 100 km" does not snake-case cleanly, so it is named explicitly.
        b.Property(x => x.BaselineConsumptionLPer100Km).HasColumnName("baseline_consumption_l_per_100km");
    }
}

internal sealed class DeviceConfiguration : IEntityTypeConfiguration<Device>
{
    public void Configure(EntityTypeBuilder<Device> b)
    {
        b.ToTable("devices");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.HasOne(x => x.Vehicle).WithMany().HasForeignKey(x => x.VehicleId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne<Device>().WithMany().HasForeignKey(x => x.ParentDeviceId).OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class ProduceTypeConfiguration : IEntityTypeConfiguration<ProduceType>
{
    public void Configure(EntityTypeBuilder<ProduceType> b)
    {
        b.ToTable("produce_types");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class TripConfiguration : IEntityTypeConfiguration<Trip>
{
    public void Configure(EntityTypeBuilder<Trip> b)
    {
        b.ToTable("trips");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.Ignore(x => x.IsEnded);
        b.Ignore(x => x.IsMoving);
        b.Ignore(x => x.Thresholds);
        b.Property(x => x.Version).HasColumnName("xmin").HasColumnType("xid").ValueGeneratedOnAddOrUpdate().IsConcurrencyToken();
        b.HasOne(x => x.Vehicle).WithMany().HasForeignKey(x => x.VehicleId).OnDelete(DeleteBehavior.Restrict);
        b.HasOne(x => x.Driver).WithMany().HasForeignKey(x => x.DriverId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne(x => x.Device).WithMany().HasForeignKey(x => x.DeviceId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne(x => x.LogisticsPartner).WithMany().HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Restrict);
        b.HasOne(x => x.AgroProcessor).WithMany().HasForeignKey(x => x.AgroProcessorId).OnDelete(DeleteBehavior.Restrict);
        b.HasOne<AdminUser>().WithMany().HasForeignKey(x => x.CreatedByAdminId).OnDelete(DeleteBehavior.SetNull);
        b.HasMany(x => x.Produce).WithOne().HasForeignKey(x => x.TripId).OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class TripProduceConfiguration : IEntityTypeConfiguration<TripProduce>
{
    public void Configure(EntityTypeBuilder<TripProduce> b)
    {
        b.ToTable("trip_produce");
        b.HasKey(x => new { x.TripId, x.ProduceTypeId });
        b.HasOne(x => x.ProduceType).WithMany().HasForeignKey(x => x.ProduceTypeId).OnDelete(DeleteBehavior.Restrict);
    }
}

internal sealed class SensorReadingConfiguration : IEntityTypeConfiguration<SensorReading>
{
    public void Configure(EntityTypeBuilder<SensorReading> b)
    {
        b.ToTable("sensor_readings");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).UseIdentityAlwaysColumn();
        b.HasOne<Device>().WithMany().HasForeignKey(x => x.DeviceId).OnDelete(DeleteBehavior.Cascade);
        b.HasOne<Trip>().WithMany().HasForeignKey(x => x.TripId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne<Vehicle>().WithMany().HasForeignKey(x => x.VehicleId).OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class AlertRuleConfiguration : IEntityTypeConfiguration<AlertRule>
{
    public void Configure(EntityTypeBuilder<AlertRule> b)
    {
        b.ToTable("alert_rules");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class NotificationChannelSettingConfiguration : IEntityTypeConfiguration<NotificationChannelSetting>
{
    public void Configure(EntityTypeBuilder<NotificationChannelSetting> b)
    {
        b.ToTable("notification_channel_settings");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
    }
}

internal sealed class AlertConfiguration : IEntityTypeConfiguration<Alert>
{
    public void Configure(EntityTypeBuilder<Alert> b)
    {
        b.ToTable("alerts");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.Ignore(x => x.IsOpen);
        b.HasOne(x => x.Device).WithMany().HasForeignKey(x => x.DeviceId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne(x => x.Trip).WithMany().HasForeignKey(x => x.TripId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne<Vehicle>().WithMany().HasForeignKey(x => x.VehicleId).OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class NotificationConfiguration : IEntityTypeConfiguration<Notification>
{
    public void Configure(EntityTypeBuilder<Notification> b)
    {
        b.ToTable("notifications");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.HasOne(x => x.LogisticsPartner).WithMany().HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class NotificationDeliveryConfiguration : IEntityTypeConfiguration<NotificationDelivery>
{
    public void Configure(EntityTypeBuilder<NotificationDelivery> b)
    {
        b.ToTable("notification_deliveries");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.HasOne<Alert>().WithMany().HasForeignKey(x => x.AlertId).OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class ShareLinkConfiguration : IEntityTypeConfiguration<ShareLink>
{
    public void Configure(EntityTypeBuilder<ShareLink> b)
    {
        b.ToTable("share_links");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.HasOne(x => x.LogisticsPartner).WithMany().HasForeignKey(x => x.LogisticsPartnerId).OnDelete(DeleteBehavior.Cascade);
        b.HasOne(x => x.AgroProcessor).WithMany().HasForeignKey(x => x.AgroProcessorId).OnDelete(DeleteBehavior.Cascade);
        b.HasOne<AdminUser>().WithMany().HasForeignKey(x => x.CreatedByAdminId).OnDelete(DeleteBehavior.SetNull);
        b.HasMany(x => x.Trips).WithOne(x => x.ShareLink).HasForeignKey(x => x.ShareLinkId).OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class ShareLinkTripConfiguration : IEntityTypeConfiguration<ShareLinkTrip>
{
    public void Configure(EntityTypeBuilder<ShareLinkTrip> b)
    {
        b.ToTable("share_link_trips");
        b.HasKey(x => new { x.ShareLinkId, x.TripId });
        b.HasOne(x => x.Trip).WithMany().HasForeignKey(x => x.TripId).OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class AuditLogConfiguration : IEntityTypeConfiguration<AuditLog>
{
    public void Configure(EntityTypeBuilder<AuditLog> b)
    {
        b.ToTable("audit_logs");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).UseIdentityAlwaysColumn();
        b.Property(x => x.Details).HasColumnType("jsonb");
    }
}

internal sealed class RouteRecommendationConfiguration : IEntityTypeConfiguration<RouteRecommendation>
{
    public void Configure(EntityTypeBuilder<RouteRecommendation> b)
    {
        b.ToTable("route_recommendations");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.Property(x => x.RoutesJson).HasColumnType("jsonb");
        b.Property(x => x.AdviceJson).HasColumnType("jsonb");
        b.HasOne<Trip>().WithMany().HasForeignKey(x => x.TripId).OnDelete(DeleteBehavior.Cascade);
    }
}

internal sealed class FuelPriceConfiguration : IEntityTypeConfiguration<FuelPrice>
{
    public void Configure(EntityTypeBuilder<FuelPrice> b)
    {
        b.ToTable("fuel_prices");
        b.HasKey(x => x.FuelType);
        b.Property(x => x.FuelType).ValueGeneratedNever();
        b.HasOne<AdminUser>().WithMany().HasForeignKey(x => x.UpdatedByAdminId).OnDelete(DeleteBehavior.SetNull);
    }
}

internal sealed class FuelEstimateConfiguration : IEntityTypeConfiguration<FuelEstimate>
{
    public void Configure(EntityTypeBuilder<FuelEstimate> b)
    {
        b.ToTable("fuel_estimates");
        b.HasKey(x => x.Id);
        b.Property(x => x.Id).ValueGeneratedNever();
        b.Property(x => x.BreakdownJson).HasColumnName("breakdown_json").HasColumnType("jsonb");
        b.Property(x => x.AssumptionsJson).HasColumnName("assumptions_json").HasColumnType("jsonb");
        b.Property(x => x.LitresPer100Km).HasColumnName("litres_per100km");
        b.HasOne<Trip>().WithMany().HasForeignKey(x => x.TripId).OnDelete(DeleteBehavior.Cascade);
        b.HasOne<Vehicle>().WithMany().HasForeignKey(x => x.VehicleId).OnDelete(DeleteBehavior.SetNull);
        b.HasOne<AdminUser>().WithMany().HasForeignKey(x => x.CreatedByAdminId).OnDelete(DeleteBehavior.SetNull);
    }
}
