-- =====================================================================================
-- WonderFleet — V001 initial schema (single consolidated migration)
-- Owner: Ofemini Global Limited / OfeminiAgricTech
-- Applied automatically at startup by the in-app migration runner (schema_migrations),
-- inside one transaction guarded by a PostgreSQL advisory lock.
-- Conventions: snake_case, uuid PKs (UUIDv7 generated by the app), timestamptz in UTC,
-- enums stored as text with CHECK constraints, soft delete via deleted_at.
-- =====================================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;   -- fast ILIKE search on names

-- ------------------------------------------------------------------ code sequences ---
CREATE SEQUENCE IF NOT EXISTS admin_code_seq    START 1;
CREATE SEQUENCE IF NOT EXISTS partner_code_seq  START 1;
CREATE SEQUENCE IF NOT EXISTS processor_code_seq START 1;
CREATE SEQUENCE IF NOT EXISTS vehicle_code_seq  START 1001;
CREATE SEQUENCE IF NOT EXISTS trip_code_seq     START 1;

-- ------------------------------------------------------------------ identity --------
CREATE TABLE admin_users (
    id                   uuid PRIMARY KEY,
    admin_code           varchar(20)  NOT NULL UNIQUE,
    full_name            varchar(150) NOT NULL,
    email                varchar(254) NOT NULL,
    normalized_email     varchar(254) NOT NULL UNIQUE,
    phone_number         varchar(20),
    address              varchar(300),
    photo_path           varchar(400),
    password_hash        varchar(200) NOT NULL,
    role                 varchar(40)  NOT NULL CHECK (role IN ('SuperAdmin','Admin')),
    is_active            boolean      NOT NULL DEFAULT true,
    must_change_password boolean      NOT NULL DEFAULT false,
    failed_login_count   integer      NOT NULL DEFAULT 0,
    lockout_end          timestamptz,
    last_login_at        timestamptz,
    password_changed_at  timestamptz,
    security_stamp       varchar(64)  NOT NULL,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    updated_at           timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE refresh_tokens (
    id                     uuid PRIMARY KEY,
    admin_user_id          uuid         NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
    token_hash             varchar(128) NOT NULL UNIQUE,
    family_id              uuid         NOT NULL,
    expires_at             timestamptz  NOT NULL,
    created_at             timestamptz  NOT NULL,
    created_by_ip          varchar(64),
    revoked_at             timestamptz,
    revoked_by_ip          varchar(64),
    replaced_by_token_hash varchar(128),
    revoked_reason         varchar(100)
);
CREATE INDEX ix_refresh_tokens_admin_user_id ON refresh_tokens (admin_user_id);
CREATE INDEX ix_refresh_tokens_family_id     ON refresh_tokens (family_id);

-- ------------------------------------------------------------------ partners --------
CREATE TABLE logistics_partners (
    id                      uuid PRIMARY KEY,
    partner_code            varchar(20)  NOT NULL UNIQUE,
    company_name            varchar(200) NOT NULL,
    contact_person          varchar(150) NOT NULL,
    cac_number              varchar(30)  NOT NULL,
    phone_number            varchar(20)  NOT NULL,
    email                   varchar(254) NOT NULL,
    office_address          varchar(300),
    city                    varchar(100),
    state                   varchar(100),
    photo_path              varchar(400),
    fleet_size              integer      NOT NULL DEFAULT 0 CHECK (fleet_size >= 0),
    driver_pool_size        integer      NOT NULL DEFAULT 0 CHECK (driver_pool_size >= 0),
    years_of_operation      integer      NOT NULL DEFAULT 0 CHECK (years_of_operation >= 0),
    availability_status     varchar(40)  NOT NULL CHECK (availability_status IN ('AvailableNow','AvailableSoon','FullyBooked','Unavailable')),
    insurance_coverage_type varchar(40)  CHECK (insurance_coverage_type IN ('GoodsInTransit','ComprehensiveFleet','ThirdParty','MarineCargo','Other')),
    insurance_expiry_date   date,
    status                  varchar(40)  NOT NULL CHECK (status IN ('Pending','Active','Suspended')),
    onboarded_at            timestamptz,
    deleted_at              timestamptz,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_logistics_partners_cac   ON logistics_partners (lower(cac_number)) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ux_logistics_partners_email ON logistics_partners (lower(email))      WHERE deleted_at IS NULL;
CREATE INDEX ix_logistics_partners_status       ON logistics_partners (status) WHERE deleted_at IS NULL;
CREATE INDEX ix_logistics_partners_name_trgm    ON logistics_partners USING gin (lower(company_name) gin_trgm_ops);

CREATE TABLE partner_truck_types (
    id                   uuid PRIMARY KEY,
    logistics_partner_id uuid          NOT NULL REFERENCES logistics_partners(id) ON DELETE CASCADE,
    truck_type           varchar(60)   NOT NULL,
    max_tonnage          numeric(8,2)  NOT NULL CHECK (max_tonnage > 0),
    quantity             integer       NOT NULL CHECK (quantity > 0)
);
CREATE INDEX ix_partner_truck_types_partner ON partner_truck_types (logistics_partner_id);

CREATE TABLE partner_corridors (
    id                   uuid PRIMARY KEY,
    logistics_partner_id uuid         NOT NULL REFERENCES logistics_partners(id) ON DELETE CASCADE,
    name                 varchar(120) NOT NULL
);
CREATE INDEX ix_partner_corridors_partner ON partner_corridors (logistics_partner_id);

CREATE TABLE partner_documents (
    id                   uuid PRIMARY KEY,
    logistics_partner_id uuid         NOT NULL REFERENCES logistics_partners(id) ON DELETE CASCADE,
    document_type        varchar(40)  NOT NULL CHECK (document_type IN ('CacCertificate','InsurancePolicy','RegisteredDrivers','VehicleLicense','Other')),
    file_name            varchar(255) NOT NULL,
    storage_path         varchar(400) NOT NULL,
    content_type         varchar(100) NOT NULL,
    size_bytes           bigint       NOT NULL CHECK (size_bytes > 0),
    is_verified          boolean      NOT NULL DEFAULT false,
    expires_on           date,
    uploaded_at          timestamptz  NOT NULL
);
CREATE INDEX ix_partner_documents_partner ON partner_documents (logistics_partner_id);

CREATE TABLE agro_processors (
    id             uuid PRIMARY KEY,
    processor_code varchar(20)  NOT NULL UNIQUE,
    name           varchar(200) NOT NULL,
    address        varchar(300) NOT NULL,
    latitude       double precision,
    longitude      double precision,
    city           varchar(100),
    state          varchar(100),
    photo_path     varchar(400),
    status         varchar(40)  NOT NULL CHECK (status IN ('Pending','Active','Suspended')),
    deleted_at     timestamptz,
    created_at     timestamptz  NOT NULL DEFAULT now(),
    updated_at     timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_agro_processors_status    ON agro_processors (status) WHERE deleted_at IS NULL;
CREATE INDEX ix_agro_processors_name_trgm ON agro_processors USING gin (lower(name) gin_trgm_ops);

CREATE TABLE agro_processor_contacts (
    id                uuid PRIMARY KEY,
    agro_processor_id uuid         NOT NULL REFERENCES agro_processors(id) ON DELETE CASCADE,
    full_name         varchar(150) NOT NULL,
    phone_number      varchar(20)  NOT NULL,
    email             varchar(254) NOT NULL,
    is_primary        boolean      NOT NULL DEFAULT false
);
CREATE INDEX ix_agro_processor_contacts_processor ON agro_processor_contacts (agro_processor_id);
CREATE UNIQUE INDEX ux_agro_processor_contacts_primary ON agro_processor_contacts (agro_processor_id) WHERE is_primary;

-- ------------------------------------------------------------------ fleet -----------
CREATE TABLE drivers (
    id                   uuid PRIMARY KEY,
    logistics_partner_id uuid         NOT NULL REFERENCES logistics_partners(id) ON DELETE RESTRICT,
    full_name            varchar(150) NOT NULL,
    phone_number         varchar(20)  NOT NULL,
    license_number       varchar(40),
    home_base            varchar(100),
    rating               numeric(2,1) NOT NULL DEFAULT 5.0 CHECK (rating BETWEEN 0 AND 5),
    completed_trips      integer      NOT NULL DEFAULT 0,
    status               varchar(40)  NOT NULL CHECK (status IN ('Available','OnTrip','OffDuty')),
    deleted_at           timestamptz,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    updated_at           timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_drivers_partner_status ON drivers (logistics_partner_id, status) WHERE deleted_at IS NULL;
CREATE INDEX ix_drivers_name_trgm      ON drivers USING gin (lower(full_name) gin_trgm_ops);

CREATE TABLE vehicles (
    id                   uuid PRIMARY KEY,
    vehicle_code         varchar(20)  NOT NULL UNIQUE,
    fleet_number         varchar(30)  NOT NULL,
    license_number       varchar(30)  NOT NULL,
    vehicle_type         varchar(60)  NOT NULL,
    capacity_tonnes      numeric(8,2) NOT NULL CHECK (capacity_tonnes > 0),
    year_of_manufacture  integer      CHECK (year_of_manufacture BETWEEN 1950 AND 2100),
    logistics_partner_id uuid         NOT NULL REFERENCES logistics_partners(id) ON DELETE RESTRICT,
    status               varchar(40)  NOT NULL CHECK (status IN ('Active','Maintenance','Inactive')),
    deleted_at           timestamptz,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    updated_at           timestamptz  NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX ux_vehicles_fleet_number   ON vehicles (upper(fleet_number))   WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX ux_vehicles_license_number ON vehicles (upper(license_number)) WHERE deleted_at IS NULL;
CREATE INDEX ix_vehicles_partner               ON vehicles (logistics_partner_id) WHERE deleted_at IS NULL;

CREATE TABLE devices (
    id                uuid PRIMARY KEY,
    serial            varchar(40)  NOT NULL UNIQUE,
    firebase_key      varchar(100) NOT NULL UNIQUE,
    kind              varchar(40)  NOT NULL CHECK (kind IN ('Master','SubUnit')),
    parent_device_id  uuid REFERENCES devices(id) ON DELETE SET NULL,
    vehicle_id        uuid REFERENCES vehicles(id) ON DELETE SET NULL,
    firmware_version  varchar(40),
    battery_level     integer CHECK (battery_level BETWEEN 0 AND 100),
    is_online         boolean      NOT NULL DEFAULT false,
    last_seen_at      timestamptz,
    last_changed_at   timestamptz,
    last_temperature  numeric(5,2),
    last_humidity     numeric(5,2),
    last_latitude     double precision,
    last_longitude    double precision,
    last_payload_hash varchar(64),
    created_at        timestamptz  NOT NULL DEFAULT now(),
    updated_at        timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_devices_vehicle ON devices (vehicle_id);

CREATE TABLE produce_types (
    id                      uuid PRIMARY KEY,
    name                    varchar(80) NOT NULL,
    default_min_temperature numeric(5,2),
    default_max_temperature numeric(5,2),
    default_min_humidity    numeric(5,2),
    default_max_humidity    numeric(5,2)
);
CREATE UNIQUE INDEX ux_produce_types_name ON produce_types (lower(name));

-- ------------------------------------------------------------------ trips -----------
CREATE TABLE trips (
    id                      uuid PRIMARY KEY,
    trip_code               varchar(20)  NOT NULL UNIQUE,
    vehicle_id              uuid         NOT NULL REFERENCES vehicles(id) ON DELETE RESTRICT,
    driver_id               uuid         REFERENCES drivers(id) ON DELETE SET NULL,
    device_id               uuid         REFERENCES devices(id) ON DELETE SET NULL,
    logistics_partner_id    uuid         NOT NULL REFERENCES logistics_partners(id) ON DELETE RESTRICT,
    agro_processor_id       uuid         NOT NULL REFERENCES agro_processors(id) ON DELETE RESTRICT,
    status                  varchar(40)  NOT NULL CHECK (status IN ('Scheduled','InTransit','Delayed','Stopped','Completed','Cancelled')),
    sensor_status           varchar(40)  NOT NULL CHECK (sensor_status IN ('Normal','Warning','Critical','Offline')),
    estimated_weight_tonnes numeric(8,2) NOT NULL CHECK (estimated_weight_tonnes >= 0),
    packaging_type          varchar(40)  CHECK (packaging_type IN ('Crates','Sacks','Cartons','Baskets','Pallets','ReeferContainer','Bulk','Other')),
    unit_count              integer      CHECK (unit_count >= 0),
    additional_notes        varchar(1000),
    pickup_address          varchar(300) NOT NULL,
    origin_label            varchar(100) NOT NULL,
    pickup_latitude         double precision,
    pickup_longitude        double precision,
    destination_address     varchar(300) NOT NULL,
    destination_label       varchar(100) NOT NULL,
    destination_latitude    double precision,
    destination_longitude   double precision,
    loading_time            timestamptz  NOT NULL,
    expected_arrival        timestamptz  NOT NULL,
    started_at              timestamptz,
    completed_at            timestamptz,
    cancelled_at            timestamptz,
    min_temperature         numeric(5,2) NOT NULL,
    max_temperature         numeric(5,2) NOT NULL,
    min_humidity            numeric(5,2) NOT NULL,
    max_humidity            numeric(5,2) NOT NULL,
    last_latitude           double precision,
    last_longitude          double precision,
    last_speed_kmh          double precision,
    last_position_at        timestamptz,
    last_moved_at           timestamptz,
    distance_travelled_km   double precision NOT NULL DEFAULT 0,
    planned_distance_km     double precision,
    co2_emission_kg         numeric(12,2) NOT NULL DEFAULT 0,
    last_temperature        numeric(5,2),
    last_humidity           numeric(5,2),
    created_by_admin_id     uuid REFERENCES admin_users(id) ON DELETE SET NULL,
    created_at              timestamptz  NOT NULL DEFAULT now(),
    updated_at              timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_trips_temperature_range CHECK (min_temperature < max_temperature),
    CONSTRAINT ck_trips_humidity_range    CHECK (min_humidity < max_humidity),
    CONSTRAINT ck_trips_arrival_after_loading CHECK (expected_arrival > loading_time)
);
CREATE INDEX ix_trips_status               ON trips (status);
CREATE INDEX ix_trips_partner_status       ON trips (logistics_partner_id, status);
CREATE INDEX ix_trips_processor_status     ON trips (agro_processor_id, status);
CREATE INDEX ix_trips_vehicle              ON trips (vehicle_id);
CREATE INDEX ix_trips_created_at           ON trips (created_at DESC);
-- A device/vehicle can only be on one live trip at a time.
CREATE UNIQUE INDEX ux_trips_active_device  ON trips (device_id)  WHERE status IN ('Scheduled','InTransit','Delayed','Stopped') AND device_id IS NOT NULL;
CREATE UNIQUE INDEX ux_trips_active_vehicle ON trips (vehicle_id) WHERE status IN ('Scheduled','InTransit','Delayed','Stopped');

CREATE TABLE trip_produce (
    trip_id         uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    produce_type_id uuid NOT NULL REFERENCES produce_types(id) ON DELETE RESTRICT,
    PRIMARY KEY (trip_id, produce_type_id)
);

-- ------------------------------------------------------------------ telemetry -------
CREATE TABLE sensor_readings (
    id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    device_id     uuid        NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    trip_id       uuid        REFERENCES trips(id) ON DELETE SET NULL,
    vehicle_id    uuid        REFERENCES vehicles(id) ON DELETE SET NULL,
    temperature   numeric(5,2),
    humidity      numeric(5,2),
    latitude      double precision,
    longitude     double precision,
    speed_kmh     double precision,
    battery_level integer,
    is_active     boolean     NOT NULL,
    source        varchar(40) NOT NULL CHECK (source IN ('Firebase','Webhook')),
    recorded_at   timestamptz NOT NULL,
    received_at   timestamptz NOT NULL
);
CREATE INDEX ix_sensor_readings_trip_time   ON sensor_readings (trip_id, recorded_at DESC);
CREATE INDEX ix_sensor_readings_device_time ON sensor_readings (device_id, recorded_at DESC);
-- BRIN keeps fleet-wide time-range scans (analytics/reports) cheap as the table grows.
CREATE INDEX brin_sensor_readings_recorded  ON sensor_readings USING brin (recorded_at);

-- ------------------------------------------------------------------ alerting --------
CREATE TABLE alert_rules (
    id               uuid PRIMARY KEY,
    alert_type       varchar(40)  NOT NULL UNIQUE,
    name             varchar(100) NOT NULL,
    description      varchar(300) NOT NULL,
    is_enabled       boolean      NOT NULL DEFAULT true,
    threshold_value  numeric(8,2),
    duration_minutes integer,
    created_at       timestamptz  NOT NULL DEFAULT now(),
    updated_at       timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE notification_channel_settings (
    id            uuid PRIMARY KEY,
    channel       varchar(20) NOT NULL UNIQUE CHECK (channel IN ('Email','Sms')),
    is_enabled    boolean     NOT NULL DEFAULT true,
    critical_only boolean     NOT NULL DEFAULT true,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE alerts (
    id                      uuid PRIMARY KEY,
    alert_type              varchar(40)  NOT NULL,
    severity                varchar(40)  NOT NULL CHECK (severity IN ('Informational','Warning','Critical')),
    status                  varchar(40)  NOT NULL CHECK (status IN ('Active','Acknowledged','Resolved')),
    title                   varchar(150) NOT NULL,
    message                 varchar(500) NOT NULL,
    device_id               uuid REFERENCES devices(id) ON DELETE SET NULL,
    trip_id                 uuid REFERENCES trips(id) ON DELETE SET NULL,
    vehicle_id              uuid REFERENCES vehicles(id) ON DELETE SET NULL,
    reading_value           numeric(8,2),
    secondary_reading_value numeric(8,2),
    threshold_value         numeric(8,2),
    triggered_at            timestamptz NOT NULL,
    last_triggered_at       timestamptz NOT NULL,
    occurrence_count        integer     NOT NULL DEFAULT 1,
    acknowledged_at         timestamptz,
    acknowledged_by         uuid,
    resolved_at             timestamptz,
    resolved_by             uuid,
    resolution_note         varchar(500),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_alerts_status_severity ON alerts (status, severity, last_triggered_at DESC);
CREATE INDEX ix_alerts_trip            ON alerts (trip_id);
CREATE INDEX ix_alerts_triggered_at    ON alerts (triggered_at DESC);
-- One open alert per (device, type): repeated breaches escalate the same row instead of spamming.
CREATE UNIQUE INDEX ux_alerts_open_device_type ON alerts (device_id, alert_type) WHERE status <> 'Resolved' AND device_id IS NOT NULL;

CREATE TABLE notifications (
    id                   uuid PRIMARY KEY,
    category             varchar(40)  NOT NULL CHECK (category IN ('Hardware','Critical','Partner','System')),
    title                varchar(150) NOT NULL,
    message              varchar(500) NOT NULL,
    related_entity_type  varchar(60),
    related_entity_id    uuid,
    logistics_partner_id uuid REFERENCES logistics_partners(id) ON DELETE SET NULL,
    requires_review      boolean     NOT NULL DEFAULT false,
    is_read              boolean     NOT NULL DEFAULT false,
    read_at              timestamptz,
    dismissed_at         timestamptz,
    created_at           timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_notifications_feed   ON notifications (created_at DESC) WHERE dismissed_at IS NULL;
CREATE INDEX ix_notifications_unread ON notifications (is_read) WHERE dismissed_at IS NULL;

CREATE TABLE notification_deliveries (
    id                  uuid PRIMARY KEY,
    channel             varchar(20)  NOT NULL CHECK (channel IN ('Email','Sms')),
    recipient           varchar(254) NOT NULL,
    subject             varchar(200),
    body                text         NOT NULL,
    text_body           text,
    template_key        varchar(60)  NOT NULL,
    status              varchar(20)  NOT NULL CHECK (status IN ('Pending','Sending','Sent','Failed')),
    attempts            integer      NOT NULL DEFAULT 0,
    next_attempt_at     timestamptz  NOT NULL,
    last_error          varchar(1000),
    provider_message_id varchar(200),
    alert_id            uuid REFERENCES alerts(id) ON DELETE SET NULL,
    created_at          timestamptz  NOT NULL DEFAULT now(),
    sent_at             timestamptz
);
CREATE INDEX ix_notification_deliveries_due ON notification_deliveries (next_attempt_at) WHERE status = 'Pending';

-- ------------------------------------------------------------------ sharing ---------
CREATE TABLE share_links (
    id                   uuid PRIMARY KEY,
    token_hash           varchar(128) NOT NULL UNIQUE,
    token_hint           varchar(12)  NOT NULL,
    audience             varchar(40)  NOT NULL CHECK (audience IN ('LogisticsPartner','AgroProcessor')),
    logistics_partner_id uuid REFERENCES logistics_partners(id) ON DELETE CASCADE,
    agro_processor_id    uuid REFERENCES agro_processors(id) ON DELETE CASCADE,
    recipient_email      varchar(254),
    recipient_phone      varchar(20),
    expires_at           timestamptz  NOT NULL,
    revoked_at           timestamptz,
    revoked_reason       varchar(100),
    last_accessed_at     timestamptz,
    access_count         integer      NOT NULL DEFAULT 0,
    created_by_admin_id  uuid REFERENCES admin_users(id) ON DELETE SET NULL,
    created_at           timestamptz  NOT NULL DEFAULT now(),
    CONSTRAINT ck_share_links_owner CHECK (
        (audience = 'LogisticsPartner' AND logistics_partner_id IS NOT NULL AND agro_processor_id IS NULL) OR
        (audience = 'AgroProcessor'    AND agro_processor_id    IS NOT NULL AND logistics_partner_id IS NULL))
);
CREATE INDEX ix_share_links_partner   ON share_links (logistics_partner_id);
CREATE INDEX ix_share_links_processor ON share_links (agro_processor_id);
CREATE INDEX ix_share_links_live      ON share_links (expires_at) WHERE revoked_at IS NULL;

CREATE TABLE share_link_trips (
    share_link_id uuid NOT NULL REFERENCES share_links(id) ON DELETE CASCADE,
    trip_id       uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    PRIMARY KEY (share_link_id, trip_id)
);
CREATE INDEX ix_share_link_trips_trip ON share_link_trips (trip_id);

-- ------------------------------------------------------------------ route AI / audit
CREATE TABLE route_recommendations (
    id                               uuid PRIMARY KEY,
    trip_id                          uuid REFERENCES trips(id) ON DELETE CASCADE,
    origin                           varchar(300) NOT NULL,
    destination                      varchar(300) NOT NULL,
    requested_departure              timestamptz  NOT NULL,
    recommended_departure            timestamptz,
    selected_route_index             integer      NOT NULL,
    summary                          varchar(2000) NOT NULL,
    heat_risk_level                  varchar(20)  NOT NULL,
    distance_km                      double precision NOT NULL,
    duration_minutes                 integer      NOT NULL,
    encoded_polyline                 text,
    estimated_spoilage_reduction_pct numeric(5,2) NOT NULL DEFAULT 0,
    routes_json                      jsonb        NOT NULL DEFAULT '[]',
    advice_json                      jsonb        NOT NULL DEFAULT '{}',
    model                            varchar(60)  NOT NULL,
    created_at                       timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_route_recommendations_trip ON route_recommendations (trip_id, created_at DESC);

CREATE TABLE audit_logs (
    id          bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor_type  varchar(20)  NOT NULL,
    actor_id    varchar(64),
    action      varchar(100) NOT NULL,
    entity_type varchar(60),
    entity_id   varchar(64),
    ip_address  varchar(64),
    user_agent  varchar(300),
    details     jsonb,
    created_at  timestamptz  NOT NULL DEFAULT now()
);
CREATE INDEX ix_audit_logs_created_at ON audit_logs (created_at DESC);
CREATE INDEX ix_audit_logs_entity     ON audit_logs (entity_type, entity_id);

-- ------------------------------------------------------------------ reference data --
INSERT INTO alert_rules (id, alert_type, name, description, is_enabled, threshold_value, duration_minutes) VALUES
 ('0190d7a0-0000-7000-8000-000000000001','TemperatureBreach','Temp breach',   'Fallback upper temperature limit (°C) when a trip has no range', true,  8,    NULL),
 ('0190d7a0-0000-7000-8000-000000000002','HighHumidity',     'High humidity', 'Fallback upper humidity limit (% RH) when a trip has no range', true,  60,   NULL),
 ('0190d7a0-0000-7000-8000-000000000003','LowBattery',       'Low battery',   'Device battery percentage that raises an alert',              false, 15,   NULL),
 ('0190d7a0-0000-7000-8000-000000000004','Stoppage',         'Stoppage alert','Minutes a moving trip may stand still before alerting',        true,  NULL, 30),
 ('0190d7a0-0000-7000-8000-000000000005','DeviceOffline',    'Device offline','Minutes without fresh telemetry before a device is offline',   true,  NULL, 10),
 ('0190d7a0-0000-7000-8000-000000000006','Delay',            'Delivery delay','Minutes past expected arrival before a delay is raised',       true,  NULL, 30);

INSERT INTO notification_channel_settings (id, channel, is_enabled, critical_only) VALUES
 ('0190d7a0-0000-7000-8000-000000000101','Sms',   false, true),
 ('0190d7a0-0000-7000-8000-000000000102','Email', true,  true);

-- Typical safe transport ranges; admins adjust per trip. Values are prototype ranges per the concept note.
INSERT INTO produce_types (id, name, default_min_temperature, default_max_temperature, default_min_humidity, default_max_humidity) VALUES
 ('0190d7a0-0000-7000-8000-000000000201','Tomatoes', 10, 15, 85, 95),
 ('0190d7a0-0000-7000-8000-000000000202','Cassava',  20, 30, 80, 95),
 ('0190d7a0-0000-7000-8000-000000000203','Yam',      15, 28, 60, 75),
 ('0190d7a0-0000-7000-8000-000000000204','Potatoes',  4, 12, 85, 95),
 ('0190d7a0-0000-7000-8000-000000000205','Onions',    0, 30, 65, 75),
 ('0190d7a0-0000-7000-8000-000000000206','Rice',     10, 30, 40, 70),
 ('0190d7a0-0000-7000-8000-000000000207','Pepper',    7, 13, 90, 95),
 ('0190d7a0-0000-7000-8000-000000000208','Plantain', 13, 16, 85, 95);
